### ISSUE TITLE
Missing Breakpoints

### ISSUE THREAD

**Issue by cls-design** [WoltLab/woltlab.github.io#142]
The new breakpoints are missing:

https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/style/bootstrap/mixin/mediaQuery.scss#L64

**Comment by TimWolla** [comment]
Technically this would need to go into the 5.3 docs, but those are not using mkdocs, making deployment much harder. Thus I've added this issue for the 5.4 branch.
