### ISSUE TITLE
Explain how to programmatically use the imageViewer

### ISSUE THREAD

**Issue by jens1o** [WoltLab/woltlab.github.io#23]
see https://community.woltlab.com/thread/267373-bilder-im-imageviewer-öffnen/

**Comment by dtdesign** [comment]
```html
<a href="http://example.com/full.jpg" class="jsImageViewer">
	<img src="http://example.com/thumbnail.jpg">
</a>
```
… and you're done. The ImageViewer itself is loaded through the `headIncludeJavaScript.tpl` and is available everywhere without any further configuration needs.

**Comment by jens1o** [comment]
And now copy and paste that into the docs ;)

**Comment by jens1o** [comment]
Thanks.
