### ISSUE TITLE
6.0: Improve the icon migration docs on how to replace Icons at runtime

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/woltlab.github.io#338]
The docs are currently not clear about how to replace an Icon at runtime using JS.

I know, that `document.querySelector("... > fa-icon").setIcon("...")` is enough, but a short example may save developers some time.

**Comment by TimWolla** [comment]
> The docs are currently not clear about how to replace an Icon at runtime using JS.

The `setIcon()` method is documented here: https://docs.woltlab.com/6.0/migration/wsc55/icons/#changing-an-icon-on-runtime, did you see that section and would like it to be expanded or did you miss it entirely and it's sufficient?

**Comment by SoftCreatR** [comment]
I saw it, but I think, an example would be good.
