### ISSUE TITLE
6.0: Optimize documentation of Pagination WebComponent

### ISSUE THREAD

**Issue by mutec** [WoltLab/woltlab.github.io#348]
- Where should that element be located (by default)?
- What happens in case there is only one page available? Do we have to implement an `if`-case or will it be removed/hidden?
- Is the pagination meant to appear once a page only? Otherwise: How is it possible to re-use the pagination in the footer-element?

**Comment by BurntimeX** [comment]
> * Where should that element be located (by default)?

There is no specific guidance from us on this.

> * What happens in case there is only one page available? Do we have to implement an `if`-case or will it be removed/hidden?

It is already part of the documentation that the pagination is only displayed if the `count` parameter is greater than 1.

> * Is the pagination meant to appear once a page only? Otherwise: How is it possible to re-use the pagination in the footer-element?

The component can be placed on a page as many times as you want.
