### ISSUE TITLE
Wrong d.ts path

### ISSUE THREAD

**Issue by jan-hecker** [WoltLab/woltlab.github.io#358]
In the current documentation there is a tsconfig.js in this config there is a global.d.ts included. But the path of the global.d.ts is wrong. 

current path "node_modules/@woltlab/wcf/global.d.ts" 
correct path "node_modules/@woltlab/wcf/ts/global.d.ts" (Missing ts folder)

**Comment by TimWolla** [comment]
Resolved with #359 / #360.
