### ISSUE TITLE
Add more code examples to the FormBuilder documentation

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/woltlab.github.io#421]
The FormBuilder documentation is currently very abstract and contains few code examples of how to use it for certain things.

The blog article about the introduction of the FormBuilder, for example, contains some examples that could be included in the documentation:
https://www.woltlab.com/article/209-new-features-for-developers-in-woltlab-suite-5-2/

The following sections lack examples:
- [x] Overview https://docs.woltlab.com/6.1/php/api/form_builder/overview/
- [x] Form builder usage in dialogs (aka `Psr15DialogForm`); can replace the section about `DialogFormDocument`
- [x] Form data handler: https://docs.woltlab.com/6.1/php/api/form_builder/validation_data/#form-data
- [x] Several form fields: https://docs.woltlab.com/6.1/php/api/form_builder/form_fields/
- [x] (including `AclFormField`)
- [x] Form structure: https://docs.woltlab.com/6.1/php/api/form_builder/structure/#imaximumlengthformfield

**Comment by Hanashi** [comment]
@BurntimeX please also add an example for usage of `AclFormField`. Currently it's really not clear for me how to use this FormField and how to handle this data.
