### ISSUE TITLE
FormBuilder FormField missing

### ISSUE THREAD

**Issue by ilouHD** [WoltLab/woltlab.github.io#52]
Hello and good day,

I'm trying to add support to subscribe to a newsletter on my website. Adding this, I tried using the FormBuilder for the first time.

Because everyone, also guests, can subscribe to the newsletter I wanted to protect my form using a recpatcha as you do in registration and the contact-form.

I just tried adding the CaptchaFormField (located in wcf\system\form\builder\field\CaptchaFormField) to my form, but it seems I left something out or so, because the captcha isn't shown on the page and there seems to be no DOM-Element for this.

Can you please provide information in https://github.com/woltlab/woltlab.github.io/blob/master/pages/php/api/formBuilder/php_api_form_builder-form_fields.md how to use the CaptchaFormField? Is it supposed to be used in such a case?

I hope for your help.

Greetings from Germany.

**Comment by Gravatronics** [comment]
Place provide the code you used to create the form field.

**Comment by ilouHD** [comment]
I used
```
        $this->form->appendChild(
            FormContainer::create('data')
                ->label("wcf.global.form.data")
                ->appendChildren([
                    // every other children I need such as TextFormField or EmailFormField
                    CaptchaFormField::create('captcha')
                        ->label('newsletter.subscriber.recaptcha')
                        ->description('newsletter.subscriber.recaptcha.description')
                        ->required()
            ])
        );
```

**Comment by Gravatronics** [comment]
You must specify a captcha object type to be used via the `objectType()` method, for example `->objectType('com.woltlab.wcf.recaptcha')`.

**Comment by ilouHD** [comment]
Thank you, that works for now.

Nevertheless there should be any information in the documentation regarding this.
