### ISSUE TITLE
404 on dialog edit

### ISSUE THREAD

**Issue by ilouHD** [WoltLab/woltlab.github.io#90]
When clicking on "Edit on GitHub" on the page for [dialogs](https://docs.woltlab.com/javascript_new-api_dialogs.html) in the new JavaScript-API one get redirect to a non existing location on github: https://github.com/woltlab/woltlab.github.io/blob/master/pages/javascript/javascript_new-api_dialogs.md

**Comment by Gravatronics** [comment]
Will be resolved once the mkdocs version is deployed.
